' use strict';
console.log('working...');

// task:  Write a JavaScript program to create an object with keys generated by running the provided function for each key. The object will have the same values as the provided object.

// Point :  solution 1 (1) Object.keys() (2) Object.fromEntries() (3) Array.prototype.map() (4) Array.prototype.reduce()

const createObject = (obj, fn) => {
	return Object.fromEntries(
		Object.keys(obj).map((key) => [key, fn(obj[key], key, obj)]),
	);
};

console.log(createObject({ a: 1, b: 2 }, (val, key) => key + val));
console.log(createObject({ a: 1, b: 2 }, (val, key) => val));

// Point : solution 2

const createObject2 = (obj, fn) => {
	return Object.keys(obj).reduce((acc, key) => {
		acc[key] = fn(obj[key], key, obj);
		return acc;
	}, {});
};

console.log(createObject2({ a: 1, b: 2 }, (val, key) => key + val));
console.log(createObject2({ a: 1, b: 2 }, (val, key) => val));

